-- ====================================================================
-- TASK JOURNAL DATABASE SCHEMA FOR SUPABASE
-- Run this in your Supabase SQL Editor (SQL Editor -> New Query -> Run)
-- ====================================================================

-- 1. Create 'members' table
CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    mp_number TEXT NOT NULL,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create 'tasks' table
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    project_code TEXT,
    task_type TEXT,
    description TEXT,
    hours REAL,
    is_special TEXT DEFAULT 'Work',
    period_code TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for lightning fast queries
CREATE INDEX IF NOT EXISTS idx_tasks_member_date ON tasks(member_id, date);
CREATE INDEX IF NOT EXISTS idx_tasks_date ON tasks(date);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE members ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if re-running
DROP POLICY IF EXISTS "Public full access to members" ON members;
DROP POLICY IF EXISTS "Public full access to tasks" ON tasks;

-- Open policies allowing team members to view, add, and save tasks
CREATE POLICY "Public full access to members" 
    ON members FOR ALL 
    USING (true) 
    WITH CHECK (true);

CREATE POLICY "Public full access to tasks" 
    ON tasks FOR ALL 
    USING (true) 
    WITH CHECK (true);

-- 4. Seed 23 default team members
INSERT INTO members (name, mp_number) VALUES
    ('Robel', '9826'),
    ('Abebech', '9790'),
    ('Habesha', '9783'),
    ('Miki', '9771'),
    ('Henok', '9772'),
    ('Solomon', '9773'),
    ('Fanuel', '9827'),
    ('Tesfaye', '9784'),
    ('Etsubdink', '9787'),
    ('Abel', '9788'),
    ('Endris', '9789'),
    ('Temesgen', '9791'),
    ('Biruk/nardos', '9806'),
    ('Yemiserach', '9807'),
    ('Tekle', '9808'),
    ('Eyerusalem', '9810'),
    ('Ribka', '9813'),
    ('Alemu', '9814'),
    ('Dejen', '9816'),
    ('Yeabsira/Getnet.G', '9817'),
    ('Getnet.W', '9818'),
    ('Habtam', '9819'),
    ('Selam', '9828')
ON CONFLICT (name) DO UPDATE 
SET mp_number = EXCLUDED.mp_number;

-- Verification
SELECT COUNT(*) AS total_seeded_members FROM members;
